repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
    args:
    - --maxkb=100
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
  - id: prettier
    types_or:
    - markdown
- repo: https://github.com/adrienverge/yamllint
  rev: v1.27.1
  hooks:
  - id: yamllint
    args:
    - --config-file=.yamllintrc.yaml
